// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: minidfs.proto

#include "minidfs.pb.h"
#include "minidfs.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace minidfs {

static const char* MiniDFSService_method_names[] = {
  "/minidfs.MiniDFSService/StoreFile",
  "/minidfs.MiniDFSService/FetchFile",
  "/minidfs.MiniDFSService/ListAllFiles",
  "/minidfs.MiniDFSService/GetFileStatus",
  "/minidfs.MiniDFSService/GetWriteLock",
  "/minidfs.MiniDFSService/DeleteFile",
};

std::unique_ptr< MiniDFSService::Stub> MiniDFSService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MiniDFSService::Stub> stub(new MiniDFSService::Stub(channel, options));
  return stub;
}

MiniDFSService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_StoreFile_(MiniDFSService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  , rpcmethod_FetchFile_(MiniDFSService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_ListAllFiles_(MiniDFSService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetFileStatus_(MiniDFSService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetWriteLock_(MiniDFSService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteFile_(MiniDFSService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::ClientWriter< ::minidfs::FileBuffer>* MiniDFSService::Stub::StoreFileRaw(::grpc::ClientContext* context, ::minidfs::StoreFileRes* response) {
  return ::grpc::internal::ClientWriterFactory< ::minidfs::FileBuffer>::Create(channel_.get(), rpcmethod_StoreFile_, context, response);
}

void MiniDFSService::Stub::async::StoreFile(::grpc::ClientContext* context, ::minidfs::StoreFileRes* response, ::grpc::ClientWriteReactor< ::minidfs::FileBuffer>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::minidfs::FileBuffer>::Create(stub_->channel_.get(), stub_->rpcmethod_StoreFile_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::minidfs::FileBuffer>* MiniDFSService::Stub::AsyncStoreFileRaw(::grpc::ClientContext* context, ::minidfs::StoreFileRes* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::minidfs::FileBuffer>::Create(channel_.get(), cq, rpcmethod_StoreFile_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::minidfs::FileBuffer>* MiniDFSService::Stub::PrepareAsyncStoreFileRaw(::grpc::ClientContext* context, ::minidfs::StoreFileRes* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::minidfs::FileBuffer>::Create(channel_.get(), cq, rpcmethod_StoreFile_, context, response, false, nullptr);
}

::grpc::ClientReader< ::minidfs::FileBuffer>* MiniDFSService::Stub::FetchFileRaw(::grpc::ClientContext* context, const ::minidfs::FetchFileReq& request) {
  return ::grpc::internal::ClientReaderFactory< ::minidfs::FileBuffer>::Create(channel_.get(), rpcmethod_FetchFile_, context, request);
}

void MiniDFSService::Stub::async::FetchFile(::grpc::ClientContext* context, const ::minidfs::FetchFileReq* request, ::grpc::ClientReadReactor< ::minidfs::FileBuffer>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::minidfs::FileBuffer>::Create(stub_->channel_.get(), stub_->rpcmethod_FetchFile_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::minidfs::FileBuffer>* MiniDFSService::Stub::AsyncFetchFileRaw(::grpc::ClientContext* context, const ::minidfs::FetchFileReq& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::minidfs::FileBuffer>::Create(channel_.get(), cq, rpcmethod_FetchFile_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::minidfs::FileBuffer>* MiniDFSService::Stub::PrepareAsyncFetchFileRaw(::grpc::ClientContext* context, const ::minidfs::FetchFileReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::minidfs::FileBuffer>::Create(channel_.get(), cq, rpcmethod_FetchFile_, context, request, false, nullptr);
}

::grpc::Status MiniDFSService::Stub::ListAllFiles(::grpc::ClientContext* context, const ::minidfs::ListAllFilesReq& request, ::minidfs::ListAllFilesRes* response) {
  return ::grpc::internal::BlockingUnaryCall< ::minidfs::ListAllFilesReq, ::minidfs::ListAllFilesRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListAllFiles_, context, request, response);
}

void MiniDFSService::Stub::async::ListAllFiles(::grpc::ClientContext* context, const ::minidfs::ListAllFilesReq* request, ::minidfs::ListAllFilesRes* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::minidfs::ListAllFilesReq, ::minidfs::ListAllFilesRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListAllFiles_, context, request, response, std::move(f));
}

void MiniDFSService::Stub::async::ListAllFiles(::grpc::ClientContext* context, const ::minidfs::ListAllFilesReq* request, ::minidfs::ListAllFilesRes* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListAllFiles_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::minidfs::ListAllFilesRes>* MiniDFSService::Stub::PrepareAsyncListAllFilesRaw(::grpc::ClientContext* context, const ::minidfs::ListAllFilesReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::minidfs::ListAllFilesRes, ::minidfs::ListAllFilesReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListAllFiles_, context, request);
}

::grpc::ClientAsyncResponseReader< ::minidfs::ListAllFilesRes>* MiniDFSService::Stub::AsyncListAllFilesRaw(::grpc::ClientContext* context, const ::minidfs::ListAllFilesReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListAllFilesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MiniDFSService::Stub::GetFileStatus(::grpc::ClientContext* context, const ::minidfs::FileStatusReq& request, ::minidfs::FileInfo* response) {
  return ::grpc::internal::BlockingUnaryCall< ::minidfs::FileStatusReq, ::minidfs::FileInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetFileStatus_, context, request, response);
}

void MiniDFSService::Stub::async::GetFileStatus(::grpc::ClientContext* context, const ::minidfs::FileStatusReq* request, ::minidfs::FileInfo* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::minidfs::FileStatusReq, ::minidfs::FileInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetFileStatus_, context, request, response, std::move(f));
}

void MiniDFSService::Stub::async::GetFileStatus(::grpc::ClientContext* context, const ::minidfs::FileStatusReq* request, ::minidfs::FileInfo* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetFileStatus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::minidfs::FileInfo>* MiniDFSService::Stub::PrepareAsyncGetFileStatusRaw(::grpc::ClientContext* context, const ::minidfs::FileStatusReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::minidfs::FileInfo, ::minidfs::FileStatusReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetFileStatus_, context, request);
}

::grpc::ClientAsyncResponseReader< ::minidfs::FileInfo>* MiniDFSService::Stub::AsyncGetFileStatusRaw(::grpc::ClientContext* context, const ::minidfs::FileStatusReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetFileStatusRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MiniDFSService::Stub::GetWriteLock(::grpc::ClientContext* context, const ::minidfs::WriteLockReq& request, ::minidfs::WriteLockRes* response) {
  return ::grpc::internal::BlockingUnaryCall< ::minidfs::WriteLockReq, ::minidfs::WriteLockRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetWriteLock_, context, request, response);
}

void MiniDFSService::Stub::async::GetWriteLock(::grpc::ClientContext* context, const ::minidfs::WriteLockReq* request, ::minidfs::WriteLockRes* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::minidfs::WriteLockReq, ::minidfs::WriteLockRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetWriteLock_, context, request, response, std::move(f));
}

void MiniDFSService::Stub::async::GetWriteLock(::grpc::ClientContext* context, const ::minidfs::WriteLockReq* request, ::minidfs::WriteLockRes* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetWriteLock_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::minidfs::WriteLockRes>* MiniDFSService::Stub::PrepareAsyncGetWriteLockRaw(::grpc::ClientContext* context, const ::minidfs::WriteLockReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::minidfs::WriteLockRes, ::minidfs::WriteLockReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetWriteLock_, context, request);
}

::grpc::ClientAsyncResponseReader< ::minidfs::WriteLockRes>* MiniDFSService::Stub::AsyncGetWriteLockRaw(::grpc::ClientContext* context, const ::minidfs::WriteLockReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetWriteLockRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MiniDFSService::Stub::DeleteFile(::grpc::ClientContext* context, const ::minidfs::DeleteFileReq& request, ::minidfs::DeleteFileRes* response) {
  return ::grpc::internal::BlockingUnaryCall< ::minidfs::DeleteFileReq, ::minidfs::DeleteFileRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteFile_, context, request, response);
}

void MiniDFSService::Stub::async::DeleteFile(::grpc::ClientContext* context, const ::minidfs::DeleteFileReq* request, ::minidfs::DeleteFileRes* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::minidfs::DeleteFileReq, ::minidfs::DeleteFileRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteFile_, context, request, response, std::move(f));
}

void MiniDFSService::Stub::async::DeleteFile(::grpc::ClientContext* context, const ::minidfs::DeleteFileReq* request, ::minidfs::DeleteFileRes* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteFile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::minidfs::DeleteFileRes>* MiniDFSService::Stub::PrepareAsyncDeleteFileRaw(::grpc::ClientContext* context, const ::minidfs::DeleteFileReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::minidfs::DeleteFileRes, ::minidfs::DeleteFileReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteFile_, context, request);
}

::grpc::ClientAsyncResponseReader< ::minidfs::DeleteFileRes>* MiniDFSService::Stub::AsyncDeleteFileRaw(::grpc::ClientContext* context, const ::minidfs::DeleteFileReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteFileRaw(context, request, cq);
  result->StartCall();
  return result;
}

MiniDFSService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MiniDFSService_method_names[0],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< MiniDFSService::Service, ::minidfs::FileBuffer, ::minidfs::StoreFileRes>(
          [](MiniDFSService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::minidfs::FileBuffer>* reader,
             ::minidfs::StoreFileRes* resp) {
               return service->StoreFile(ctx, reader, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MiniDFSService_method_names[1],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< MiniDFSService::Service, ::minidfs::FetchFileReq, ::minidfs::FileBuffer>(
          [](MiniDFSService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::minidfs::FetchFileReq* req,
             ::grpc::ServerWriter<::minidfs::FileBuffer>* writer) {
               return service->FetchFile(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MiniDFSService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MiniDFSService::Service, ::minidfs::ListAllFilesReq, ::minidfs::ListAllFilesRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MiniDFSService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::minidfs::ListAllFilesReq* req,
             ::minidfs::ListAllFilesRes* resp) {
               return service->ListAllFiles(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MiniDFSService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MiniDFSService::Service, ::minidfs::FileStatusReq, ::minidfs::FileInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MiniDFSService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::minidfs::FileStatusReq* req,
             ::minidfs::FileInfo* resp) {
               return service->GetFileStatus(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MiniDFSService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MiniDFSService::Service, ::minidfs::WriteLockReq, ::minidfs::WriteLockRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MiniDFSService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::minidfs::WriteLockReq* req,
             ::minidfs::WriteLockRes* resp) {
               return service->GetWriteLock(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MiniDFSService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MiniDFSService::Service, ::minidfs::DeleteFileReq, ::minidfs::DeleteFileRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MiniDFSService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::minidfs::DeleteFileReq* req,
             ::minidfs::DeleteFileRes* resp) {
               return service->DeleteFile(ctx, req, resp);
             }, this)));
}

MiniDFSService::Service::~Service() {
}

::grpc::Status MiniDFSService::Service::StoreFile(::grpc::ServerContext* context, ::grpc::ServerReader< ::minidfs::FileBuffer>* reader, ::minidfs::StoreFileRes* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MiniDFSService::Service::FetchFile(::grpc::ServerContext* context, const ::minidfs::FetchFileReq* request, ::grpc::ServerWriter< ::minidfs::FileBuffer>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MiniDFSService::Service::ListAllFiles(::grpc::ServerContext* context, const ::minidfs::ListAllFilesReq* request, ::minidfs::ListAllFilesRes* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MiniDFSService::Service::GetFileStatus(::grpc::ServerContext* context, const ::minidfs::FileStatusReq* request, ::minidfs::FileInfo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MiniDFSService::Service::GetWriteLock(::grpc::ServerContext* context, const ::minidfs::WriteLockReq* request, ::minidfs::WriteLockRes* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MiniDFSService::Service::DeleteFile(::grpc::ServerContext* context, const ::minidfs::DeleteFileReq* request, ::minidfs::DeleteFileRes* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace minidfs
#include <grpcpp/ports_undef.inc>

