// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: minidfs.proto
#ifndef GRPC_minidfs_2eproto__INCLUDED
#define GRPC_minidfs_2eproto__INCLUDED

#include "minidfs.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace minidfs {

// service methods for minidfs
class MiniDFSService final {
 public:
  static constexpr char const* service_full_name() {
    return "minidfs.MiniDFSService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Add your service calls here
    //
    // 1. REQUIRED (Parts 1 & 2): A method to store files on the server
    std::unique_ptr< ::grpc::ClientWriterInterface< ::minidfs::FileBuffer>> StoreFile(::grpc::ClientContext* context, ::minidfs::StoreFileRes* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::minidfs::FileBuffer>>(StoreFileRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::minidfs::FileBuffer>> AsyncStoreFile(::grpc::ClientContext* context, ::minidfs::StoreFileRes* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::minidfs::FileBuffer>>(AsyncStoreFileRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::minidfs::FileBuffer>> PrepareAsyncStoreFile(::grpc::ClientContext* context, ::minidfs::StoreFileRes* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::minidfs::FileBuffer>>(PrepareAsyncStoreFileRaw(context, response, cq));
    }
    // 2. REQUIRED (Parts 1 & 2): A method to fetch files from the server
    std::unique_ptr< ::grpc::ClientReaderInterface< ::minidfs::FileBuffer>> FetchFile(::grpc::ClientContext* context, const ::minidfs::FetchFileReq& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::minidfs::FileBuffer>>(FetchFileRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::minidfs::FileBuffer>> AsyncFetchFile(::grpc::ClientContext* context, const ::minidfs::FetchFileReq& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::minidfs::FileBuffer>>(AsyncFetchFileRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::minidfs::FileBuffer>> PrepareAsyncFetchFile(::grpc::ClientContext* context, const ::minidfs::FetchFileReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::minidfs::FileBuffer>>(PrepareAsyncFetchFileRaw(context, request, cq));
    }
    // 3. REQUIRED (Parts 1 & 2): A method to list all files on the server
    virtual ::grpc::Status ListAllFiles(::grpc::ClientContext* context, const ::minidfs::ListAllFilesReq& request, ::minidfs::ListAllFilesRes* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::minidfs::ListAllFilesRes>> AsyncListAllFiles(::grpc::ClientContext* context, const ::minidfs::ListAllFilesReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::minidfs::ListAllFilesRes>>(AsyncListAllFilesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::minidfs::ListAllFilesRes>> PrepareAsyncListAllFiles(::grpc::ClientContext* context, const ::minidfs::ListAllFilesReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::minidfs::ListAllFilesRes>>(PrepareAsyncListAllFilesRaw(context, request, cq));
    }
    // 4. REQUIRED (Parts 1 & 2): A method to get the status of a file on the server
    virtual ::grpc::Status GetFileStatus(::grpc::ClientContext* context, const ::minidfs::FileStatusReq& request, ::minidfs::FileInfo* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::minidfs::FileInfo>> AsyncGetFileStatus(::grpc::ClientContext* context, const ::minidfs::FileStatusReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::minidfs::FileInfo>>(AsyncGetFileStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::minidfs::FileInfo>> PrepareAsyncGetFileStatus(::grpc::ClientContext* context, const ::minidfs::FileStatusReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::minidfs::FileInfo>>(PrepareAsyncGetFileStatusRaw(context, request, cq));
    }
    // Get a file write lock
    virtual ::grpc::Status GetWriteLock(::grpc::ClientContext* context, const ::minidfs::WriteLockReq& request, ::minidfs::WriteLockRes* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::minidfs::WriteLockRes>> AsyncGetWriteLock(::grpc::ClientContext* context, const ::minidfs::WriteLockReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::minidfs::WriteLockRes>>(AsyncGetWriteLockRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::minidfs::WriteLockRes>> PrepareAsyncGetWriteLock(::grpc::ClientContext* context, const ::minidfs::WriteLockReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::minidfs::WriteLockRes>>(PrepareAsyncGetWriteLockRaw(context, request, cq));
    }
    // Delete file request
    virtual ::grpc::Status DeleteFile(::grpc::ClientContext* context, const ::minidfs::DeleteFileReq& request, ::minidfs::DeleteFileRes* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::minidfs::DeleteFileRes>> AsyncDeleteFile(::grpc::ClientContext* context, const ::minidfs::DeleteFileReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::minidfs::DeleteFileRes>>(AsyncDeleteFileRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::minidfs::DeleteFileRes>> PrepareAsyncDeleteFile(::grpc::ClientContext* context, const ::minidfs::DeleteFileReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::minidfs::DeleteFileRes>>(PrepareAsyncDeleteFileRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Add your service calls here
      //
      // 1. REQUIRED (Parts 1 & 2): A method to store files on the server
      virtual void StoreFile(::grpc::ClientContext* context, ::minidfs::StoreFileRes* response, ::grpc::ClientWriteReactor< ::minidfs::FileBuffer>* reactor) = 0;
      // 2. REQUIRED (Parts 1 & 2): A method to fetch files from the server
      virtual void FetchFile(::grpc::ClientContext* context, const ::minidfs::FetchFileReq* request, ::grpc::ClientReadReactor< ::minidfs::FileBuffer>* reactor) = 0;
      // 3. REQUIRED (Parts 1 & 2): A method to list all files on the server
      virtual void ListAllFiles(::grpc::ClientContext* context, const ::minidfs::ListAllFilesReq* request, ::minidfs::ListAllFilesRes* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ListAllFiles(::grpc::ClientContext* context, const ::minidfs::ListAllFilesReq* request, ::minidfs::ListAllFilesRes* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 4. REQUIRED (Parts 1 & 2): A method to get the status of a file on the server
      virtual void GetFileStatus(::grpc::ClientContext* context, const ::minidfs::FileStatusReq* request, ::minidfs::FileInfo* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetFileStatus(::grpc::ClientContext* context, const ::minidfs::FileStatusReq* request, ::minidfs::FileInfo* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Get a file write lock
      virtual void GetWriteLock(::grpc::ClientContext* context, const ::minidfs::WriteLockReq* request, ::minidfs::WriteLockRes* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetWriteLock(::grpc::ClientContext* context, const ::minidfs::WriteLockReq* request, ::minidfs::WriteLockRes* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Delete file request
      virtual void DeleteFile(::grpc::ClientContext* context, const ::minidfs::DeleteFileReq* request, ::minidfs::DeleteFileRes* response, std::function<void(::grpc::Status)>) = 0;
      virtual void DeleteFile(::grpc::ClientContext* context, const ::minidfs::DeleteFileReq* request, ::minidfs::DeleteFileRes* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientWriterInterface< ::minidfs::FileBuffer>* StoreFileRaw(::grpc::ClientContext* context, ::minidfs::StoreFileRes* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::minidfs::FileBuffer>* AsyncStoreFileRaw(::grpc::ClientContext* context, ::minidfs::StoreFileRes* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::minidfs::FileBuffer>* PrepareAsyncStoreFileRaw(::grpc::ClientContext* context, ::minidfs::StoreFileRes* response, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::minidfs::FileBuffer>* FetchFileRaw(::grpc::ClientContext* context, const ::minidfs::FetchFileReq& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::minidfs::FileBuffer>* AsyncFetchFileRaw(::grpc::ClientContext* context, const ::minidfs::FetchFileReq& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::minidfs::FileBuffer>* PrepareAsyncFetchFileRaw(::grpc::ClientContext* context, const ::minidfs::FetchFileReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::minidfs::ListAllFilesRes>* AsyncListAllFilesRaw(::grpc::ClientContext* context, const ::minidfs::ListAllFilesReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::minidfs::ListAllFilesRes>* PrepareAsyncListAllFilesRaw(::grpc::ClientContext* context, const ::minidfs::ListAllFilesReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::minidfs::FileInfo>* AsyncGetFileStatusRaw(::grpc::ClientContext* context, const ::minidfs::FileStatusReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::minidfs::FileInfo>* PrepareAsyncGetFileStatusRaw(::grpc::ClientContext* context, const ::minidfs::FileStatusReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::minidfs::WriteLockRes>* AsyncGetWriteLockRaw(::grpc::ClientContext* context, const ::minidfs::WriteLockReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::minidfs::WriteLockRes>* PrepareAsyncGetWriteLockRaw(::grpc::ClientContext* context, const ::minidfs::WriteLockReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::minidfs::DeleteFileRes>* AsyncDeleteFileRaw(::grpc::ClientContext* context, const ::minidfs::DeleteFileReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::minidfs::DeleteFileRes>* PrepareAsyncDeleteFileRaw(::grpc::ClientContext* context, const ::minidfs::DeleteFileReq& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientWriter< ::minidfs::FileBuffer>> StoreFile(::grpc::ClientContext* context, ::minidfs::StoreFileRes* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::minidfs::FileBuffer>>(StoreFileRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::minidfs::FileBuffer>> AsyncStoreFile(::grpc::ClientContext* context, ::minidfs::StoreFileRes* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::minidfs::FileBuffer>>(AsyncStoreFileRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::minidfs::FileBuffer>> PrepareAsyncStoreFile(::grpc::ClientContext* context, ::minidfs::StoreFileRes* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::minidfs::FileBuffer>>(PrepareAsyncStoreFileRaw(context, response, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::minidfs::FileBuffer>> FetchFile(::grpc::ClientContext* context, const ::minidfs::FetchFileReq& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::minidfs::FileBuffer>>(FetchFileRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::minidfs::FileBuffer>> AsyncFetchFile(::grpc::ClientContext* context, const ::minidfs::FetchFileReq& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::minidfs::FileBuffer>>(AsyncFetchFileRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::minidfs::FileBuffer>> PrepareAsyncFetchFile(::grpc::ClientContext* context, const ::minidfs::FetchFileReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::minidfs::FileBuffer>>(PrepareAsyncFetchFileRaw(context, request, cq));
    }
    ::grpc::Status ListAllFiles(::grpc::ClientContext* context, const ::minidfs::ListAllFilesReq& request, ::minidfs::ListAllFilesRes* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::minidfs::ListAllFilesRes>> AsyncListAllFiles(::grpc::ClientContext* context, const ::minidfs::ListAllFilesReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::minidfs::ListAllFilesRes>>(AsyncListAllFilesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::minidfs::ListAllFilesRes>> PrepareAsyncListAllFiles(::grpc::ClientContext* context, const ::minidfs::ListAllFilesReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::minidfs::ListAllFilesRes>>(PrepareAsyncListAllFilesRaw(context, request, cq));
    }
    ::grpc::Status GetFileStatus(::grpc::ClientContext* context, const ::minidfs::FileStatusReq& request, ::minidfs::FileInfo* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::minidfs::FileInfo>> AsyncGetFileStatus(::grpc::ClientContext* context, const ::minidfs::FileStatusReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::minidfs::FileInfo>>(AsyncGetFileStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::minidfs::FileInfo>> PrepareAsyncGetFileStatus(::grpc::ClientContext* context, const ::minidfs::FileStatusReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::minidfs::FileInfo>>(PrepareAsyncGetFileStatusRaw(context, request, cq));
    }
    ::grpc::Status GetWriteLock(::grpc::ClientContext* context, const ::minidfs::WriteLockReq& request, ::minidfs::WriteLockRes* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::minidfs::WriteLockRes>> AsyncGetWriteLock(::grpc::ClientContext* context, const ::minidfs::WriteLockReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::minidfs::WriteLockRes>>(AsyncGetWriteLockRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::minidfs::WriteLockRes>> PrepareAsyncGetWriteLock(::grpc::ClientContext* context, const ::minidfs::WriteLockReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::minidfs::WriteLockRes>>(PrepareAsyncGetWriteLockRaw(context, request, cq));
    }
    ::grpc::Status DeleteFile(::grpc::ClientContext* context, const ::minidfs::DeleteFileReq& request, ::minidfs::DeleteFileRes* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::minidfs::DeleteFileRes>> AsyncDeleteFile(::grpc::ClientContext* context, const ::minidfs::DeleteFileReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::minidfs::DeleteFileRes>>(AsyncDeleteFileRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::minidfs::DeleteFileRes>> PrepareAsyncDeleteFile(::grpc::ClientContext* context, const ::minidfs::DeleteFileReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::minidfs::DeleteFileRes>>(PrepareAsyncDeleteFileRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void StoreFile(::grpc::ClientContext* context, ::minidfs::StoreFileRes* response, ::grpc::ClientWriteReactor< ::minidfs::FileBuffer>* reactor) override;
      void FetchFile(::grpc::ClientContext* context, const ::minidfs::FetchFileReq* request, ::grpc::ClientReadReactor< ::minidfs::FileBuffer>* reactor) override;
      void ListAllFiles(::grpc::ClientContext* context, const ::minidfs::ListAllFilesReq* request, ::minidfs::ListAllFilesRes* response, std::function<void(::grpc::Status)>) override;
      void ListAllFiles(::grpc::ClientContext* context, const ::minidfs::ListAllFilesReq* request, ::minidfs::ListAllFilesRes* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetFileStatus(::grpc::ClientContext* context, const ::minidfs::FileStatusReq* request, ::minidfs::FileInfo* response, std::function<void(::grpc::Status)>) override;
      void GetFileStatus(::grpc::ClientContext* context, const ::minidfs::FileStatusReq* request, ::minidfs::FileInfo* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetWriteLock(::grpc::ClientContext* context, const ::minidfs::WriteLockReq* request, ::minidfs::WriteLockRes* response, std::function<void(::grpc::Status)>) override;
      void GetWriteLock(::grpc::ClientContext* context, const ::minidfs::WriteLockReq* request, ::minidfs::WriteLockRes* response, ::grpc::ClientUnaryReactor* reactor) override;
      void DeleteFile(::grpc::ClientContext* context, const ::minidfs::DeleteFileReq* request, ::minidfs::DeleteFileRes* response, std::function<void(::grpc::Status)>) override;
      void DeleteFile(::grpc::ClientContext* context, const ::minidfs::DeleteFileReq* request, ::minidfs::DeleteFileRes* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientWriter< ::minidfs::FileBuffer>* StoreFileRaw(::grpc::ClientContext* context, ::minidfs::StoreFileRes* response) override;
    ::grpc::ClientAsyncWriter< ::minidfs::FileBuffer>* AsyncStoreFileRaw(::grpc::ClientContext* context, ::minidfs::StoreFileRes* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::minidfs::FileBuffer>* PrepareAsyncStoreFileRaw(::grpc::ClientContext* context, ::minidfs::StoreFileRes* response, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::minidfs::FileBuffer>* FetchFileRaw(::grpc::ClientContext* context, const ::minidfs::FetchFileReq& request) override;
    ::grpc::ClientAsyncReader< ::minidfs::FileBuffer>* AsyncFetchFileRaw(::grpc::ClientContext* context, const ::minidfs::FetchFileReq& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::minidfs::FileBuffer>* PrepareAsyncFetchFileRaw(::grpc::ClientContext* context, const ::minidfs::FetchFileReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::minidfs::ListAllFilesRes>* AsyncListAllFilesRaw(::grpc::ClientContext* context, const ::minidfs::ListAllFilesReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::minidfs::ListAllFilesRes>* PrepareAsyncListAllFilesRaw(::grpc::ClientContext* context, const ::minidfs::ListAllFilesReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::minidfs::FileInfo>* AsyncGetFileStatusRaw(::grpc::ClientContext* context, const ::minidfs::FileStatusReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::minidfs::FileInfo>* PrepareAsyncGetFileStatusRaw(::grpc::ClientContext* context, const ::minidfs::FileStatusReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::minidfs::WriteLockRes>* AsyncGetWriteLockRaw(::grpc::ClientContext* context, const ::minidfs::WriteLockReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::minidfs::WriteLockRes>* PrepareAsyncGetWriteLockRaw(::grpc::ClientContext* context, const ::minidfs::WriteLockReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::minidfs::DeleteFileRes>* AsyncDeleteFileRaw(::grpc::ClientContext* context, const ::minidfs::DeleteFileReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::minidfs::DeleteFileRes>* PrepareAsyncDeleteFileRaw(::grpc::ClientContext* context, const ::minidfs::DeleteFileReq& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_StoreFile_;
    const ::grpc::internal::RpcMethod rpcmethod_FetchFile_;
    const ::grpc::internal::RpcMethod rpcmethod_ListAllFiles_;
    const ::grpc::internal::RpcMethod rpcmethod_GetFileStatus_;
    const ::grpc::internal::RpcMethod rpcmethod_GetWriteLock_;
    const ::grpc::internal::RpcMethod rpcmethod_DeleteFile_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Add your service calls here
    //
    // 1. REQUIRED (Parts 1 & 2): A method to store files on the server
    virtual ::grpc::Status StoreFile(::grpc::ServerContext* context, ::grpc::ServerReader< ::minidfs::FileBuffer>* reader, ::minidfs::StoreFileRes* response);
    // 2. REQUIRED (Parts 1 & 2): A method to fetch files from the server
    virtual ::grpc::Status FetchFile(::grpc::ServerContext* context, const ::minidfs::FetchFileReq* request, ::grpc::ServerWriter< ::minidfs::FileBuffer>* writer);
    // 3. REQUIRED (Parts 1 & 2): A method to list all files on the server
    virtual ::grpc::Status ListAllFiles(::grpc::ServerContext* context, const ::minidfs::ListAllFilesReq* request, ::minidfs::ListAllFilesRes* response);
    // 4. REQUIRED (Parts 1 & 2): A method to get the status of a file on the server
    virtual ::grpc::Status GetFileStatus(::grpc::ServerContext* context, const ::minidfs::FileStatusReq* request, ::minidfs::FileInfo* response);
    // Get a file write lock
    virtual ::grpc::Status GetWriteLock(::grpc::ServerContext* context, const ::minidfs::WriteLockReq* request, ::minidfs::WriteLockRes* response);
    // Delete file request
    virtual ::grpc::Status DeleteFile(::grpc::ServerContext* context, const ::minidfs::DeleteFileReq* request, ::minidfs::DeleteFileRes* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_StoreFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StoreFile() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_StoreFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StoreFile(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::minidfs::FileBuffer>* /*reader*/, ::minidfs::StoreFileRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStoreFile(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::minidfs::StoreFileRes, ::minidfs::FileBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_FetchFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_FetchFile() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_FetchFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchFile(::grpc::ServerContext* /*context*/, const ::minidfs::FetchFileReq* /*request*/, ::grpc::ServerWriter< ::minidfs::FileBuffer>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFetchFile(::grpc::ServerContext* context, ::minidfs::FetchFileReq* request, ::grpc::ServerAsyncWriter< ::minidfs::FileBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ListAllFiles : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ListAllFiles() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_ListAllFiles() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListAllFiles(::grpc::ServerContext* /*context*/, const ::minidfs::ListAllFilesReq* /*request*/, ::minidfs::ListAllFilesRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListAllFiles(::grpc::ServerContext* context, ::minidfs::ListAllFilesReq* request, ::grpc::ServerAsyncResponseWriter< ::minidfs::ListAllFilesRes>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetFileStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetFileStatus() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_GetFileStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFileStatus(::grpc::ServerContext* /*context*/, const ::minidfs::FileStatusReq* /*request*/, ::minidfs::FileInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetFileStatus(::grpc::ServerContext* context, ::minidfs::FileStatusReq* request, ::grpc::ServerAsyncResponseWriter< ::minidfs::FileInfo>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetWriteLock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetWriteLock() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_GetWriteLock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetWriteLock(::grpc::ServerContext* /*context*/, const ::minidfs::WriteLockReq* /*request*/, ::minidfs::WriteLockRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetWriteLock(::grpc::ServerContext* context, ::minidfs::WriteLockReq* request, ::grpc::ServerAsyncResponseWriter< ::minidfs::WriteLockRes>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DeleteFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DeleteFile() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_DeleteFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteFile(::grpc::ServerContext* /*context*/, const ::minidfs::DeleteFileReq* /*request*/, ::minidfs::DeleteFileRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeleteFile(::grpc::ServerContext* context, ::minidfs::DeleteFileReq* request, ::grpc::ServerAsyncResponseWriter< ::minidfs::DeleteFileRes>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_StoreFile<WithAsyncMethod_FetchFile<WithAsyncMethod_ListAllFiles<WithAsyncMethod_GetFileStatus<WithAsyncMethod_GetWriteLock<WithAsyncMethod_DeleteFile<Service > > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_StoreFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StoreFile() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackClientStreamingHandler< ::minidfs::FileBuffer, ::minidfs::StoreFileRes>(
            [this](
                   ::grpc::CallbackServerContext* context, ::minidfs::StoreFileRes* response) { return this->StoreFile(context, response); }));
    }
    ~WithCallbackMethod_StoreFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StoreFile(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::minidfs::FileBuffer>* /*reader*/, ::minidfs::StoreFileRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::minidfs::FileBuffer>* StoreFile(
      ::grpc::CallbackServerContext* /*context*/, ::minidfs::StoreFileRes* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_FetchFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_FetchFile() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::minidfs::FetchFileReq, ::minidfs::FileBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::minidfs::FetchFileReq* request) { return this->FetchFile(context, request); }));
    }
    ~WithCallbackMethod_FetchFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchFile(::grpc::ServerContext* /*context*/, const ::minidfs::FetchFileReq* /*request*/, ::grpc::ServerWriter< ::minidfs::FileBuffer>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::minidfs::FileBuffer>* FetchFile(
      ::grpc::CallbackServerContext* /*context*/, const ::minidfs::FetchFileReq* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ListAllFiles : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ListAllFiles() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::minidfs::ListAllFilesReq, ::minidfs::ListAllFilesRes>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::minidfs::ListAllFilesReq* request, ::minidfs::ListAllFilesRes* response) { return this->ListAllFiles(context, request, response); }));}
    void SetMessageAllocatorFor_ListAllFiles(
        ::grpc::MessageAllocator< ::minidfs::ListAllFilesReq, ::minidfs::ListAllFilesRes>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::minidfs::ListAllFilesReq, ::minidfs::ListAllFilesRes>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ListAllFiles() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListAllFiles(::grpc::ServerContext* /*context*/, const ::minidfs::ListAllFilesReq* /*request*/, ::minidfs::ListAllFilesRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListAllFiles(
      ::grpc::CallbackServerContext* /*context*/, const ::minidfs::ListAllFilesReq* /*request*/, ::minidfs::ListAllFilesRes* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetFileStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetFileStatus() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::minidfs::FileStatusReq, ::minidfs::FileInfo>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::minidfs::FileStatusReq* request, ::minidfs::FileInfo* response) { return this->GetFileStatus(context, request, response); }));}
    void SetMessageAllocatorFor_GetFileStatus(
        ::grpc::MessageAllocator< ::minidfs::FileStatusReq, ::minidfs::FileInfo>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::minidfs::FileStatusReq, ::minidfs::FileInfo>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetFileStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFileStatus(::grpc::ServerContext* /*context*/, const ::minidfs::FileStatusReq* /*request*/, ::minidfs::FileInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetFileStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::minidfs::FileStatusReq* /*request*/, ::minidfs::FileInfo* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetWriteLock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetWriteLock() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::minidfs::WriteLockReq, ::minidfs::WriteLockRes>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::minidfs::WriteLockReq* request, ::minidfs::WriteLockRes* response) { return this->GetWriteLock(context, request, response); }));}
    void SetMessageAllocatorFor_GetWriteLock(
        ::grpc::MessageAllocator< ::minidfs::WriteLockReq, ::minidfs::WriteLockRes>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::minidfs::WriteLockReq, ::minidfs::WriteLockRes>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetWriteLock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetWriteLock(::grpc::ServerContext* /*context*/, const ::minidfs::WriteLockReq* /*request*/, ::minidfs::WriteLockRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetWriteLock(
      ::grpc::CallbackServerContext* /*context*/, const ::minidfs::WriteLockReq* /*request*/, ::minidfs::WriteLockRes* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_DeleteFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DeleteFile() {
      ::grpc::Service::MarkMethodCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::minidfs::DeleteFileReq, ::minidfs::DeleteFileRes>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::minidfs::DeleteFileReq* request, ::minidfs::DeleteFileRes* response) { return this->DeleteFile(context, request, response); }));}
    void SetMessageAllocatorFor_DeleteFile(
        ::grpc::MessageAllocator< ::minidfs::DeleteFileReq, ::minidfs::DeleteFileRes>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(5);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::minidfs::DeleteFileReq, ::minidfs::DeleteFileRes>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_DeleteFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteFile(::grpc::ServerContext* /*context*/, const ::minidfs::DeleteFileReq* /*request*/, ::minidfs::DeleteFileRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DeleteFile(
      ::grpc::CallbackServerContext* /*context*/, const ::minidfs::DeleteFileReq* /*request*/, ::minidfs::DeleteFileRes* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_StoreFile<WithCallbackMethod_FetchFile<WithCallbackMethod_ListAllFiles<WithCallbackMethod_GetFileStatus<WithCallbackMethod_GetWriteLock<WithCallbackMethod_DeleteFile<Service > > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_StoreFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StoreFile() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_StoreFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StoreFile(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::minidfs::FileBuffer>* /*reader*/, ::minidfs::StoreFileRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_FetchFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_FetchFile() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_FetchFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchFile(::grpc::ServerContext* /*context*/, const ::minidfs::FetchFileReq* /*request*/, ::grpc::ServerWriter< ::minidfs::FileBuffer>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ListAllFiles : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ListAllFiles() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_ListAllFiles() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListAllFiles(::grpc::ServerContext* /*context*/, const ::minidfs::ListAllFilesReq* /*request*/, ::minidfs::ListAllFilesRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetFileStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetFileStatus() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_GetFileStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFileStatus(::grpc::ServerContext* /*context*/, const ::minidfs::FileStatusReq* /*request*/, ::minidfs::FileInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetWriteLock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetWriteLock() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_GetWriteLock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetWriteLock(::grpc::ServerContext* /*context*/, const ::minidfs::WriteLockReq* /*request*/, ::minidfs::WriteLockRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DeleteFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DeleteFile() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_DeleteFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteFile(::grpc::ServerContext* /*context*/, const ::minidfs::DeleteFileReq* /*request*/, ::minidfs::DeleteFileRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_StoreFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StoreFile() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_StoreFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StoreFile(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::minidfs::FileBuffer>* /*reader*/, ::minidfs::StoreFileRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStoreFile(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_FetchFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_FetchFile() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_FetchFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchFile(::grpc::ServerContext* /*context*/, const ::minidfs::FetchFileReq* /*request*/, ::grpc::ServerWriter< ::minidfs::FileBuffer>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFetchFile(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ListAllFiles : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ListAllFiles() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_ListAllFiles() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListAllFiles(::grpc::ServerContext* /*context*/, const ::minidfs::ListAllFilesReq* /*request*/, ::minidfs::ListAllFilesRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListAllFiles(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetFileStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetFileStatus() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_GetFileStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFileStatus(::grpc::ServerContext* /*context*/, const ::minidfs::FileStatusReq* /*request*/, ::minidfs::FileInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetFileStatus(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetWriteLock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetWriteLock() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_GetWriteLock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetWriteLock(::grpc::ServerContext* /*context*/, const ::minidfs::WriteLockReq* /*request*/, ::minidfs::WriteLockRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetWriteLock(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_DeleteFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DeleteFile() {
      ::grpc::Service::MarkMethodRaw(5);
    }
    ~WithRawMethod_DeleteFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteFile(::grpc::ServerContext* /*context*/, const ::minidfs::DeleteFileReq* /*request*/, ::minidfs::DeleteFileRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeleteFile(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StoreFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StoreFile() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackClientStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, ::grpc::ByteBuffer* response) { return this->StoreFile(context, response); }));
    }
    ~WithRawCallbackMethod_StoreFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StoreFile(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::minidfs::FileBuffer>* /*reader*/, ::minidfs::StoreFileRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::grpc::ByteBuffer>* StoreFile(
      ::grpc::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_FetchFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_FetchFile() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->FetchFile(context, request); }));
    }
    ~WithRawCallbackMethod_FetchFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchFile(::grpc::ServerContext* /*context*/, const ::minidfs::FetchFileReq* /*request*/, ::grpc::ServerWriter< ::minidfs::FileBuffer>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* FetchFile(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ListAllFiles : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ListAllFiles() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ListAllFiles(context, request, response); }));
    }
    ~WithRawCallbackMethod_ListAllFiles() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListAllFiles(::grpc::ServerContext* /*context*/, const ::minidfs::ListAllFilesReq* /*request*/, ::minidfs::ListAllFilesRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListAllFiles(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetFileStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetFileStatus() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetFileStatus(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetFileStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFileStatus(::grpc::ServerContext* /*context*/, const ::minidfs::FileStatusReq* /*request*/, ::minidfs::FileInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetFileStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetWriteLock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetWriteLock() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetWriteLock(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetWriteLock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetWriteLock(::grpc::ServerContext* /*context*/, const ::minidfs::WriteLockReq* /*request*/, ::minidfs::WriteLockRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetWriteLock(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DeleteFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DeleteFile() {
      ::grpc::Service::MarkMethodRawCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DeleteFile(context, request, response); }));
    }
    ~WithRawCallbackMethod_DeleteFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteFile(::grpc::ServerContext* /*context*/, const ::minidfs::DeleteFileReq* /*request*/, ::minidfs::DeleteFileRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DeleteFile(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ListAllFiles : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ListAllFiles() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::minidfs::ListAllFilesReq, ::minidfs::ListAllFilesRes>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::minidfs::ListAllFilesReq, ::minidfs::ListAllFilesRes>* streamer) {
                       return this->StreamedListAllFiles(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ListAllFiles() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ListAllFiles(::grpc::ServerContext* /*context*/, const ::minidfs::ListAllFilesReq* /*request*/, ::minidfs::ListAllFilesRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedListAllFiles(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::minidfs::ListAllFilesReq,::minidfs::ListAllFilesRes>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetFileStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetFileStatus() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::minidfs::FileStatusReq, ::minidfs::FileInfo>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::minidfs::FileStatusReq, ::minidfs::FileInfo>* streamer) {
                       return this->StreamedGetFileStatus(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetFileStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetFileStatus(::grpc::ServerContext* /*context*/, const ::minidfs::FileStatusReq* /*request*/, ::minidfs::FileInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetFileStatus(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::minidfs::FileStatusReq,::minidfs::FileInfo>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetWriteLock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetWriteLock() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::minidfs::WriteLockReq, ::minidfs::WriteLockRes>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::minidfs::WriteLockReq, ::minidfs::WriteLockRes>* streamer) {
                       return this->StreamedGetWriteLock(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetWriteLock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetWriteLock(::grpc::ServerContext* /*context*/, const ::minidfs::WriteLockReq* /*request*/, ::minidfs::WriteLockRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetWriteLock(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::minidfs::WriteLockReq,::minidfs::WriteLockRes>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DeleteFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DeleteFile() {
      ::grpc::Service::MarkMethodStreamed(5,
        new ::grpc::internal::StreamedUnaryHandler<
          ::minidfs::DeleteFileReq, ::minidfs::DeleteFileRes>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::minidfs::DeleteFileReq, ::minidfs::DeleteFileRes>* streamer) {
                       return this->StreamedDeleteFile(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DeleteFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DeleteFile(::grpc::ServerContext* /*context*/, const ::minidfs::DeleteFileReq* /*request*/, ::minidfs::DeleteFileRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDeleteFile(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::minidfs::DeleteFileReq,::minidfs::DeleteFileRes>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ListAllFiles<WithStreamedUnaryMethod_GetFileStatus<WithStreamedUnaryMethod_GetWriteLock<WithStreamedUnaryMethod_DeleteFile<Service > > > > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_FetchFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_FetchFile() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::minidfs::FetchFileReq, ::minidfs::FileBuffer>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::minidfs::FetchFileReq, ::minidfs::FileBuffer>* streamer) {
                       return this->StreamedFetchFile(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_FetchFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status FetchFile(::grpc::ServerContext* /*context*/, const ::minidfs::FetchFileReq* /*request*/, ::grpc::ServerWriter< ::minidfs::FileBuffer>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedFetchFile(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::minidfs::FetchFileReq,::minidfs::FileBuffer>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_FetchFile<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_FetchFile<WithStreamedUnaryMethod_ListAllFiles<WithStreamedUnaryMethod_GetFileStatus<WithStreamedUnaryMethod_GetWriteLock<WithStreamedUnaryMethod_DeleteFile<Service > > > > > StreamedService;
};

}  // namespace minidfs


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_minidfs_2eproto__INCLUDED
