// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: minidfs.proto

#ifndef PROTOBUF_minidfs_2eproto__INCLUDED
#define PROTOBUF_minidfs_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace minidfs {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_minidfs_2eproto();
void protobuf_AssignDesc_minidfs_2eproto();
void protobuf_ShutdownFile_minidfs_2eproto();

class CallbackListReq;
class CallbackListRes;
class DeleteFileReq;
class DeleteFileRes;
class FetchFileReq;
class FileBuffer;
class FileInfo;
class FileStatusReq;
class ListAllFilesReq;
class ListAllFilesRes;
class StoreFileRes;
class WriteLockReq;
class WriteLockRes;

// ===================================================================

class FileBuffer : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:minidfs.FileBuffer) */ {
 public:
  FileBuffer();
  virtual ~FileBuffer();

  FileBuffer(const FileBuffer& from);

  inline FileBuffer& operator=(const FileBuffer& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FileBuffer& default_instance();

  void Swap(FileBuffer* other);

  // implements Message ----------------------------------------------

  inline FileBuffer* New() const { return New(NULL); }

  FileBuffer* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const FileBuffer& from);
  void MergeFrom(const FileBuffer& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(FileBuffer* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string client_id = 1;
  void clear_client_id();
  static const int kClientIdFieldNumber = 1;
  const ::std::string& client_id() const;
  void set_client_id(const ::std::string& value);
  void set_client_id(const char* value);
  void set_client_id(const char* value, size_t size);
  ::std::string* mutable_client_id();
  ::std::string* release_client_id();
  void set_allocated_client_id(::std::string* client_id);

  // optional string filepath = 2;
  void clear_filepath();
  static const int kFilepathFieldNumber = 2;
  const ::std::string& filepath() const;
  void set_filepath(const ::std::string& value);
  void set_filepath(const char* value);
  void set_filepath(const char* value, size_t size);
  ::std::string* mutable_filepath();
  ::std::string* release_filepath();
  void set_allocated_filepath(::std::string* filepath);

  // optional bytes data = 3;
  void clear_data();
  static const int kDataFieldNumber = 3;
  const ::std::string& data() const;
  void set_data(const ::std::string& value);
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  ::std::string* mutable_data();
  ::std::string* release_data();
  void set_allocated_data(::std::string* data);

  // optional uint64 offset = 4;
  void clear_offset();
  static const int kOffsetFieldNumber = 4;
  ::google::protobuf::uint64 offset() const;
  void set_offset(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:minidfs.FileBuffer)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr client_id_;
  ::google::protobuf::internal::ArenaStringPtr filepath_;
  ::google::protobuf::internal::ArenaStringPtr data_;
  ::google::protobuf::uint64 offset_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_minidfs_2eproto();
  friend void protobuf_AssignDesc_minidfs_2eproto();
  friend void protobuf_ShutdownFile_minidfs_2eproto();

  void InitAsDefaultInstance();
  static FileBuffer* default_instance_;
};
// -------------------------------------------------------------------

class StoreFileRes : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:minidfs.StoreFileRes) */ {
 public:
  StoreFileRes();
  virtual ~StoreFileRes();

  StoreFileRes(const StoreFileRes& from);

  inline StoreFileRes& operator=(const StoreFileRes& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StoreFileRes& default_instance();

  void Swap(StoreFileRes* other);

  // implements Message ----------------------------------------------

  inline StoreFileRes* New() const { return New(NULL); }

  StoreFileRes* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StoreFileRes& from);
  void MergeFrom(const StoreFileRes& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(StoreFileRes* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string msg = 1;
  void clear_msg();
  static const int kMsgFieldNumber = 1;
  const ::std::string& msg() const;
  void set_msg(const ::std::string& value);
  void set_msg(const char* value);
  void set_msg(const char* value, size_t size);
  ::std::string* mutable_msg();
  ::std::string* release_msg();
  void set_allocated_msg(::std::string* msg);

  // optional bool success = 2;
  void clear_success();
  static const int kSuccessFieldNumber = 2;
  bool success() const;
  void set_success(bool value);

  // @@protoc_insertion_point(class_scope:minidfs.StoreFileRes)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr msg_;
  bool success_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_minidfs_2eproto();
  friend void protobuf_AssignDesc_minidfs_2eproto();
  friend void protobuf_ShutdownFile_minidfs_2eproto();

  void InitAsDefaultInstance();
  static StoreFileRes* default_instance_;
};
// -------------------------------------------------------------------

class FetchFileReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:minidfs.FetchFileReq) */ {
 public:
  FetchFileReq();
  virtual ~FetchFileReq();

  FetchFileReq(const FetchFileReq& from);

  inline FetchFileReq& operator=(const FetchFileReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FetchFileReq& default_instance();

  void Swap(FetchFileReq* other);

  // implements Message ----------------------------------------------

  inline FetchFileReq* New() const { return New(NULL); }

  FetchFileReq* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const FetchFileReq& from);
  void MergeFrom(const FetchFileReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(FetchFileReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string filepath = 1;
  void clear_filepath();
  static const int kFilepathFieldNumber = 1;
  const ::std::string& filepath() const;
  void set_filepath(const ::std::string& value);
  void set_filepath(const char* value);
  void set_filepath(const char* value, size_t size);
  ::std::string* mutable_filepath();
  ::std::string* release_filepath();
  void set_allocated_filepath(::std::string* filepath);

  // @@protoc_insertion_point(class_scope:minidfs.FetchFileReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr filepath_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_minidfs_2eproto();
  friend void protobuf_AssignDesc_minidfs_2eproto();
  friend void protobuf_ShutdownFile_minidfs_2eproto();

  void InitAsDefaultInstance();
  static FetchFileReq* default_instance_;
};
// -------------------------------------------------------------------

class DeleteFileReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:minidfs.DeleteFileReq) */ {
 public:
  DeleteFileReq();
  virtual ~DeleteFileReq();

  DeleteFileReq(const DeleteFileReq& from);

  inline DeleteFileReq& operator=(const DeleteFileReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DeleteFileReq& default_instance();

  void Swap(DeleteFileReq* other);

  // implements Message ----------------------------------------------

  inline DeleteFileReq* New() const { return New(NULL); }

  DeleteFileReq* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DeleteFileReq& from);
  void MergeFrom(const DeleteFileReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(DeleteFileReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string filepath = 1;
  void clear_filepath();
  static const int kFilepathFieldNumber = 1;
  const ::std::string& filepath() const;
  void set_filepath(const ::std::string& value);
  void set_filepath(const char* value);
  void set_filepath(const char* value, size_t size);
  ::std::string* mutable_filepath();
  ::std::string* release_filepath();
  void set_allocated_filepath(::std::string* filepath);

  // @@protoc_insertion_point(class_scope:minidfs.DeleteFileReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr filepath_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_minidfs_2eproto();
  friend void protobuf_AssignDesc_minidfs_2eproto();
  friend void protobuf_ShutdownFile_minidfs_2eproto();

  void InitAsDefaultInstance();
  static DeleteFileReq* default_instance_;
};
// -------------------------------------------------------------------

class DeleteFileRes : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:minidfs.DeleteFileRes) */ {
 public:
  DeleteFileRes();
  virtual ~DeleteFileRes();

  DeleteFileRes(const DeleteFileRes& from);

  inline DeleteFileRes& operator=(const DeleteFileRes& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DeleteFileRes& default_instance();

  void Swap(DeleteFileRes* other);

  // implements Message ----------------------------------------------

  inline DeleteFileRes* New() const { return New(NULL); }

  DeleteFileRes* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DeleteFileRes& from);
  void MergeFrom(const DeleteFileRes& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(DeleteFileRes* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string msg = 1;
  void clear_msg();
  static const int kMsgFieldNumber = 1;
  const ::std::string& msg() const;
  void set_msg(const ::std::string& value);
  void set_msg(const char* value);
  void set_msg(const char* value, size_t size);
  ::std::string* mutable_msg();
  ::std::string* release_msg();
  void set_allocated_msg(::std::string* msg);

  // optional bool success = 2;
  void clear_success();
  static const int kSuccessFieldNumber = 2;
  bool success() const;
  void set_success(bool value);

  // @@protoc_insertion_point(class_scope:minidfs.DeleteFileRes)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr msg_;
  bool success_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_minidfs_2eproto();
  friend void protobuf_AssignDesc_minidfs_2eproto();
  friend void protobuf_ShutdownFile_minidfs_2eproto();

  void InitAsDefaultInstance();
  static DeleteFileRes* default_instance_;
};
// -------------------------------------------------------------------

class FileInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:minidfs.FileInfo) */ {
 public:
  FileInfo();
  virtual ~FileInfo();

  FileInfo(const FileInfo& from);

  inline FileInfo& operator=(const FileInfo& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FileInfo& default_instance();

  void Swap(FileInfo* other);

  // implements Message ----------------------------------------------

  inline FileInfo* New() const { return New(NULL); }

  FileInfo* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const FileInfo& from);
  void MergeFrom(const FileInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(FileInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string filepath = 1;
  void clear_filepath();
  static const int kFilepathFieldNumber = 1;
  const ::std::string& filepath() const;
  void set_filepath(const ::std::string& value);
  void set_filepath(const char* value);
  void set_filepath(const char* value, size_t size);
  ::std::string* mutable_filepath();
  ::std::string* release_filepath();
  void set_allocated_filepath(::std::string* filepath);

  // optional uint64 size = 2;
  void clear_size();
  static const int kSizeFieldNumber = 2;
  ::google::protobuf::uint64 size() const;
  void set_size(::google::protobuf::uint64 value);

  // optional uint64 last_modified = 3;
  void clear_last_modified();
  static const int kLastModifiedFieldNumber = 3;
  ::google::protobuf::uint64 last_modified() const;
  void set_last_modified(::google::protobuf::uint64 value);

  // optional uint64 created_at = 4;
  void clear_created_at();
  static const int kCreatedAtFieldNumber = 4;
  ::google::protobuf::uint64 created_at() const;
  void set_created_at(::google::protobuf::uint64 value);

  // optional uint32 crc = 5;
  void clear_crc();
  static const int kCrcFieldNumber = 5;
  ::google::protobuf::uint32 crc() const;
  void set_crc(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:minidfs.FileInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr filepath_;
  ::google::protobuf::uint64 size_;
  ::google::protobuf::uint64 last_modified_;
  ::google::protobuf::uint64 created_at_;
  ::google::protobuf::uint32 crc_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_minidfs_2eproto();
  friend void protobuf_AssignDesc_minidfs_2eproto();
  friend void protobuf_ShutdownFile_minidfs_2eproto();

  void InitAsDefaultInstance();
  static FileInfo* default_instance_;
};
// -------------------------------------------------------------------

class ListAllFilesReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:minidfs.ListAllFilesReq) */ {
 public:
  ListAllFilesReq();
  virtual ~ListAllFilesReq();

  ListAllFilesReq(const ListAllFilesReq& from);

  inline ListAllFilesReq& operator=(const ListAllFilesReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ListAllFilesReq& default_instance();

  void Swap(ListAllFilesReq* other);

  // implements Message ----------------------------------------------

  inline ListAllFilesReq* New() const { return New(NULL); }

  ListAllFilesReq* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ListAllFilesReq& from);
  void MergeFrom(const ListAllFilesReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ListAllFilesReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:minidfs.ListAllFilesReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_minidfs_2eproto();
  friend void protobuf_AssignDesc_minidfs_2eproto();
  friend void protobuf_ShutdownFile_minidfs_2eproto();

  void InitAsDefaultInstance();
  static ListAllFilesReq* default_instance_;
};
// -------------------------------------------------------------------

class ListAllFilesRes : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:minidfs.ListAllFilesRes) */ {
 public:
  ListAllFilesRes();
  virtual ~ListAllFilesRes();

  ListAllFilesRes(const ListAllFilesRes& from);

  inline ListAllFilesRes& operator=(const ListAllFilesRes& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ListAllFilesRes& default_instance();

  void Swap(ListAllFilesRes* other);

  // implements Message ----------------------------------------------

  inline ListAllFilesRes* New() const { return New(NULL); }

  ListAllFilesRes* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ListAllFilesRes& from);
  void MergeFrom(const ListAllFilesRes& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ListAllFilesRes* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .minidfs.FileInfo files = 1;
  int files_size() const;
  void clear_files();
  static const int kFilesFieldNumber = 1;
  const ::minidfs::FileInfo& files(int index) const;
  ::minidfs::FileInfo* mutable_files(int index);
  ::minidfs::FileInfo* add_files();
  ::google::protobuf::RepeatedPtrField< ::minidfs::FileInfo >*
      mutable_files();
  const ::google::protobuf::RepeatedPtrField< ::minidfs::FileInfo >&
      files() const;

  // @@protoc_insertion_point(class_scope:minidfs.ListAllFilesRes)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::minidfs::FileInfo > files_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_minidfs_2eproto();
  friend void protobuf_AssignDesc_minidfs_2eproto();
  friend void protobuf_ShutdownFile_minidfs_2eproto();

  void InitAsDefaultInstance();
  static ListAllFilesRes* default_instance_;
};
// -------------------------------------------------------------------

class FileStatusReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:minidfs.FileStatusReq) */ {
 public:
  FileStatusReq();
  virtual ~FileStatusReq();

  FileStatusReq(const FileStatusReq& from);

  inline FileStatusReq& operator=(const FileStatusReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FileStatusReq& default_instance();

  void Swap(FileStatusReq* other);

  // implements Message ----------------------------------------------

  inline FileStatusReq* New() const { return New(NULL); }

  FileStatusReq* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const FileStatusReq& from);
  void MergeFrom(const FileStatusReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(FileStatusReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string filepath = 1;
  void clear_filepath();
  static const int kFilepathFieldNumber = 1;
  const ::std::string& filepath() const;
  void set_filepath(const ::std::string& value);
  void set_filepath(const char* value);
  void set_filepath(const char* value, size_t size);
  ::std::string* mutable_filepath();
  ::std::string* release_filepath();
  void set_allocated_filepath(::std::string* filepath);

  // @@protoc_insertion_point(class_scope:minidfs.FileStatusReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr filepath_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_minidfs_2eproto();
  friend void protobuf_AssignDesc_minidfs_2eproto();
  friend void protobuf_ShutdownFile_minidfs_2eproto();

  void InitAsDefaultInstance();
  static FileStatusReq* default_instance_;
};
// -------------------------------------------------------------------

class WriteLockReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:minidfs.WriteLockReq) */ {
 public:
  WriteLockReq();
  virtual ~WriteLockReq();

  WriteLockReq(const WriteLockReq& from);

  inline WriteLockReq& operator=(const WriteLockReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const WriteLockReq& default_instance();

  void Swap(WriteLockReq* other);

  // implements Message ----------------------------------------------

  inline WriteLockReq* New() const { return New(NULL); }

  WriteLockReq* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const WriteLockReq& from);
  void MergeFrom(const WriteLockReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(WriteLockReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string client_id = 1;
  void clear_client_id();
  static const int kClientIdFieldNumber = 1;
  const ::std::string& client_id() const;
  void set_client_id(const ::std::string& value);
  void set_client_id(const char* value);
  void set_client_id(const char* value, size_t size);
  ::std::string* mutable_client_id();
  ::std::string* release_client_id();
  void set_allocated_client_id(::std::string* client_id);

  // optional string filepath = 2;
  void clear_filepath();
  static const int kFilepathFieldNumber = 2;
  const ::std::string& filepath() const;
  void set_filepath(const ::std::string& value);
  void set_filepath(const char* value);
  void set_filepath(const char* value, size_t size);
  ::std::string* mutable_filepath();
  ::std::string* release_filepath();
  void set_allocated_filepath(::std::string* filepath);

  // @@protoc_insertion_point(class_scope:minidfs.WriteLockReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr client_id_;
  ::google::protobuf::internal::ArenaStringPtr filepath_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_minidfs_2eproto();
  friend void protobuf_AssignDesc_minidfs_2eproto();
  friend void protobuf_ShutdownFile_minidfs_2eproto();

  void InitAsDefaultInstance();
  static WriteLockReq* default_instance_;
};
// -------------------------------------------------------------------

class WriteLockRes : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:minidfs.WriteLockRes) */ {
 public:
  WriteLockRes();
  virtual ~WriteLockRes();

  WriteLockRes(const WriteLockRes& from);

  inline WriteLockRes& operator=(const WriteLockRes& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const WriteLockRes& default_instance();

  void Swap(WriteLockRes* other);

  // implements Message ----------------------------------------------

  inline WriteLockRes* New() const { return New(NULL); }

  WriteLockRes* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const WriteLockRes& from);
  void MergeFrom(const WriteLockRes& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(WriteLockRes* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bool success = 1;
  void clear_success();
  static const int kSuccessFieldNumber = 1;
  bool success() const;
  void set_success(bool value);

  // @@protoc_insertion_point(class_scope:minidfs.WriteLockRes)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  bool success_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_minidfs_2eproto();
  friend void protobuf_AssignDesc_minidfs_2eproto();
  friend void protobuf_ShutdownFile_minidfs_2eproto();

  void InitAsDefaultInstance();
  static WriteLockRes* default_instance_;
};
// -------------------------------------------------------------------

class CallbackListReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:minidfs.CallbackListReq) */ {
 public:
  CallbackListReq();
  virtual ~CallbackListReq();

  CallbackListReq(const CallbackListReq& from);

  inline CallbackListReq& operator=(const CallbackListReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CallbackListReq& default_instance();

  void Swap(CallbackListReq* other);

  // implements Message ----------------------------------------------

  inline CallbackListReq* New() const { return New(NULL); }

  CallbackListReq* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CallbackListReq& from);
  void MergeFrom(const CallbackListReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CallbackListReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // @@protoc_insertion_point(class_scope:minidfs.CallbackListReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_minidfs_2eproto();
  friend void protobuf_AssignDesc_minidfs_2eproto();
  friend void protobuf_ShutdownFile_minidfs_2eproto();

  void InitAsDefaultInstance();
  static CallbackListReq* default_instance_;
};
// -------------------------------------------------------------------

class CallbackListRes : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:minidfs.CallbackListRes) */ {
 public:
  CallbackListRes();
  virtual ~CallbackListRes();

  CallbackListRes(const CallbackListRes& from);

  inline CallbackListRes& operator=(const CallbackListRes& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CallbackListRes& default_instance();

  void Swap(CallbackListRes* other);

  // implements Message ----------------------------------------------

  inline CallbackListRes* New() const { return New(NULL); }

  CallbackListRes* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CallbackListRes& from);
  void MergeFrom(const CallbackListRes& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CallbackListRes* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 version = 1;
  void clear_version();
  static const int kVersionFieldNumber = 1;
  ::google::protobuf::uint64 version() const;
  void set_version(::google::protobuf::uint64 value);

  // repeated .minidfs.FileInfo files = 2;
  int files_size() const;
  void clear_files();
  static const int kFilesFieldNumber = 2;
  const ::minidfs::FileInfo& files(int index) const;
  ::minidfs::FileInfo* mutable_files(int index);
  ::minidfs::FileInfo* add_files();
  ::google::protobuf::RepeatedPtrField< ::minidfs::FileInfo >*
      mutable_files();
  const ::google::protobuf::RepeatedPtrField< ::minidfs::FileInfo >&
      files() const;

  // @@protoc_insertion_point(class_scope:minidfs.CallbackListRes)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint64 version_;
  ::google::protobuf::RepeatedPtrField< ::minidfs::FileInfo > files_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_minidfs_2eproto();
  friend void protobuf_AssignDesc_minidfs_2eproto();
  friend void protobuf_ShutdownFile_minidfs_2eproto();

  void InitAsDefaultInstance();
  static CallbackListRes* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// FileBuffer

// optional string client_id = 1;
inline void FileBuffer::clear_client_id() {
  client_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& FileBuffer::client_id() const {
  // @@protoc_insertion_point(field_get:minidfs.FileBuffer.client_id)
  return client_id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FileBuffer::set_client_id(const ::std::string& value) {
  
  client_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:minidfs.FileBuffer.client_id)
}
inline void FileBuffer::set_client_id(const char* value) {
  
  client_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:minidfs.FileBuffer.client_id)
}
inline void FileBuffer::set_client_id(const char* value, size_t size) {
  
  client_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:minidfs.FileBuffer.client_id)
}
inline ::std::string* FileBuffer::mutable_client_id() {
  
  // @@protoc_insertion_point(field_mutable:minidfs.FileBuffer.client_id)
  return client_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* FileBuffer::release_client_id() {
  // @@protoc_insertion_point(field_release:minidfs.FileBuffer.client_id)
  
  return client_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FileBuffer::set_allocated_client_id(::std::string* client_id) {
  if (client_id != NULL) {
    
  } else {
    
  }
  client_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), client_id);
  // @@protoc_insertion_point(field_set_allocated:minidfs.FileBuffer.client_id)
}

// optional string filepath = 2;
inline void FileBuffer::clear_filepath() {
  filepath_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& FileBuffer::filepath() const {
  // @@protoc_insertion_point(field_get:minidfs.FileBuffer.filepath)
  return filepath_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FileBuffer::set_filepath(const ::std::string& value) {
  
  filepath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:minidfs.FileBuffer.filepath)
}
inline void FileBuffer::set_filepath(const char* value) {
  
  filepath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:minidfs.FileBuffer.filepath)
}
inline void FileBuffer::set_filepath(const char* value, size_t size) {
  
  filepath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:minidfs.FileBuffer.filepath)
}
inline ::std::string* FileBuffer::mutable_filepath() {
  
  // @@protoc_insertion_point(field_mutable:minidfs.FileBuffer.filepath)
  return filepath_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* FileBuffer::release_filepath() {
  // @@protoc_insertion_point(field_release:minidfs.FileBuffer.filepath)
  
  return filepath_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FileBuffer::set_allocated_filepath(::std::string* filepath) {
  if (filepath != NULL) {
    
  } else {
    
  }
  filepath_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), filepath);
  // @@protoc_insertion_point(field_set_allocated:minidfs.FileBuffer.filepath)
}

// optional bytes data = 3;
inline void FileBuffer::clear_data() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& FileBuffer::data() const {
  // @@protoc_insertion_point(field_get:minidfs.FileBuffer.data)
  return data_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FileBuffer::set_data(const ::std::string& value) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:minidfs.FileBuffer.data)
}
inline void FileBuffer::set_data(const char* value) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:minidfs.FileBuffer.data)
}
inline void FileBuffer::set_data(const void* value, size_t size) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:minidfs.FileBuffer.data)
}
inline ::std::string* FileBuffer::mutable_data() {
  
  // @@protoc_insertion_point(field_mutable:minidfs.FileBuffer.data)
  return data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* FileBuffer::release_data() {
  // @@protoc_insertion_point(field_release:minidfs.FileBuffer.data)
  
  return data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FileBuffer::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    
  } else {
    
  }
  data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:minidfs.FileBuffer.data)
}

// optional uint64 offset = 4;
inline void FileBuffer::clear_offset() {
  offset_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 FileBuffer::offset() const {
  // @@protoc_insertion_point(field_get:minidfs.FileBuffer.offset)
  return offset_;
}
inline void FileBuffer::set_offset(::google::protobuf::uint64 value) {
  
  offset_ = value;
  // @@protoc_insertion_point(field_set:minidfs.FileBuffer.offset)
}

// -------------------------------------------------------------------

// StoreFileRes

// optional string msg = 1;
inline void StoreFileRes::clear_msg() {
  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& StoreFileRes::msg() const {
  // @@protoc_insertion_point(field_get:minidfs.StoreFileRes.msg)
  return msg_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void StoreFileRes::set_msg(const ::std::string& value) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:minidfs.StoreFileRes.msg)
}
inline void StoreFileRes::set_msg(const char* value) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:minidfs.StoreFileRes.msg)
}
inline void StoreFileRes::set_msg(const char* value, size_t size) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:minidfs.StoreFileRes.msg)
}
inline ::std::string* StoreFileRes::mutable_msg() {
  
  // @@protoc_insertion_point(field_mutable:minidfs.StoreFileRes.msg)
  return msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* StoreFileRes::release_msg() {
  // @@protoc_insertion_point(field_release:minidfs.StoreFileRes.msg)
  
  return msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void StoreFileRes::set_allocated_msg(::std::string* msg) {
  if (msg != NULL) {
    
  } else {
    
  }
  msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg);
  // @@protoc_insertion_point(field_set_allocated:minidfs.StoreFileRes.msg)
}

// optional bool success = 2;
inline void StoreFileRes::clear_success() {
  success_ = false;
}
inline bool StoreFileRes::success() const {
  // @@protoc_insertion_point(field_get:minidfs.StoreFileRes.success)
  return success_;
}
inline void StoreFileRes::set_success(bool value) {
  
  success_ = value;
  // @@protoc_insertion_point(field_set:minidfs.StoreFileRes.success)
}

// -------------------------------------------------------------------

// FetchFileReq

// optional string filepath = 1;
inline void FetchFileReq::clear_filepath() {
  filepath_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& FetchFileReq::filepath() const {
  // @@protoc_insertion_point(field_get:minidfs.FetchFileReq.filepath)
  return filepath_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FetchFileReq::set_filepath(const ::std::string& value) {
  
  filepath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:minidfs.FetchFileReq.filepath)
}
inline void FetchFileReq::set_filepath(const char* value) {
  
  filepath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:minidfs.FetchFileReq.filepath)
}
inline void FetchFileReq::set_filepath(const char* value, size_t size) {
  
  filepath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:minidfs.FetchFileReq.filepath)
}
inline ::std::string* FetchFileReq::mutable_filepath() {
  
  // @@protoc_insertion_point(field_mutable:minidfs.FetchFileReq.filepath)
  return filepath_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* FetchFileReq::release_filepath() {
  // @@protoc_insertion_point(field_release:minidfs.FetchFileReq.filepath)
  
  return filepath_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FetchFileReq::set_allocated_filepath(::std::string* filepath) {
  if (filepath != NULL) {
    
  } else {
    
  }
  filepath_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), filepath);
  // @@protoc_insertion_point(field_set_allocated:minidfs.FetchFileReq.filepath)
}

// -------------------------------------------------------------------

// DeleteFileReq

// optional string filepath = 1;
inline void DeleteFileReq::clear_filepath() {
  filepath_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& DeleteFileReq::filepath() const {
  // @@protoc_insertion_point(field_get:minidfs.DeleteFileReq.filepath)
  return filepath_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DeleteFileReq::set_filepath(const ::std::string& value) {
  
  filepath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:minidfs.DeleteFileReq.filepath)
}
inline void DeleteFileReq::set_filepath(const char* value) {
  
  filepath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:minidfs.DeleteFileReq.filepath)
}
inline void DeleteFileReq::set_filepath(const char* value, size_t size) {
  
  filepath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:minidfs.DeleteFileReq.filepath)
}
inline ::std::string* DeleteFileReq::mutable_filepath() {
  
  // @@protoc_insertion_point(field_mutable:minidfs.DeleteFileReq.filepath)
  return filepath_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DeleteFileReq::release_filepath() {
  // @@protoc_insertion_point(field_release:minidfs.DeleteFileReq.filepath)
  
  return filepath_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DeleteFileReq::set_allocated_filepath(::std::string* filepath) {
  if (filepath != NULL) {
    
  } else {
    
  }
  filepath_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), filepath);
  // @@protoc_insertion_point(field_set_allocated:minidfs.DeleteFileReq.filepath)
}

// -------------------------------------------------------------------

// DeleteFileRes

// optional string msg = 1;
inline void DeleteFileRes::clear_msg() {
  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& DeleteFileRes::msg() const {
  // @@protoc_insertion_point(field_get:minidfs.DeleteFileRes.msg)
  return msg_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DeleteFileRes::set_msg(const ::std::string& value) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:minidfs.DeleteFileRes.msg)
}
inline void DeleteFileRes::set_msg(const char* value) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:minidfs.DeleteFileRes.msg)
}
inline void DeleteFileRes::set_msg(const char* value, size_t size) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:minidfs.DeleteFileRes.msg)
}
inline ::std::string* DeleteFileRes::mutable_msg() {
  
  // @@protoc_insertion_point(field_mutable:minidfs.DeleteFileRes.msg)
  return msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DeleteFileRes::release_msg() {
  // @@protoc_insertion_point(field_release:minidfs.DeleteFileRes.msg)
  
  return msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DeleteFileRes::set_allocated_msg(::std::string* msg) {
  if (msg != NULL) {
    
  } else {
    
  }
  msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg);
  // @@protoc_insertion_point(field_set_allocated:minidfs.DeleteFileRes.msg)
}

// optional bool success = 2;
inline void DeleteFileRes::clear_success() {
  success_ = false;
}
inline bool DeleteFileRes::success() const {
  // @@protoc_insertion_point(field_get:minidfs.DeleteFileRes.success)
  return success_;
}
inline void DeleteFileRes::set_success(bool value) {
  
  success_ = value;
  // @@protoc_insertion_point(field_set:minidfs.DeleteFileRes.success)
}

// -------------------------------------------------------------------

// FileInfo

// optional string filepath = 1;
inline void FileInfo::clear_filepath() {
  filepath_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& FileInfo::filepath() const {
  // @@protoc_insertion_point(field_get:minidfs.FileInfo.filepath)
  return filepath_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FileInfo::set_filepath(const ::std::string& value) {
  
  filepath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:minidfs.FileInfo.filepath)
}
inline void FileInfo::set_filepath(const char* value) {
  
  filepath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:minidfs.FileInfo.filepath)
}
inline void FileInfo::set_filepath(const char* value, size_t size) {
  
  filepath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:minidfs.FileInfo.filepath)
}
inline ::std::string* FileInfo::mutable_filepath() {
  
  // @@protoc_insertion_point(field_mutable:minidfs.FileInfo.filepath)
  return filepath_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* FileInfo::release_filepath() {
  // @@protoc_insertion_point(field_release:minidfs.FileInfo.filepath)
  
  return filepath_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FileInfo::set_allocated_filepath(::std::string* filepath) {
  if (filepath != NULL) {
    
  } else {
    
  }
  filepath_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), filepath);
  // @@protoc_insertion_point(field_set_allocated:minidfs.FileInfo.filepath)
}

// optional uint64 size = 2;
inline void FileInfo::clear_size() {
  size_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 FileInfo::size() const {
  // @@protoc_insertion_point(field_get:minidfs.FileInfo.size)
  return size_;
}
inline void FileInfo::set_size(::google::protobuf::uint64 value) {
  
  size_ = value;
  // @@protoc_insertion_point(field_set:minidfs.FileInfo.size)
}

// optional uint64 last_modified = 3;
inline void FileInfo::clear_last_modified() {
  last_modified_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 FileInfo::last_modified() const {
  // @@protoc_insertion_point(field_get:minidfs.FileInfo.last_modified)
  return last_modified_;
}
inline void FileInfo::set_last_modified(::google::protobuf::uint64 value) {
  
  last_modified_ = value;
  // @@protoc_insertion_point(field_set:minidfs.FileInfo.last_modified)
}

// optional uint64 created_at = 4;
inline void FileInfo::clear_created_at() {
  created_at_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 FileInfo::created_at() const {
  // @@protoc_insertion_point(field_get:minidfs.FileInfo.created_at)
  return created_at_;
}
inline void FileInfo::set_created_at(::google::protobuf::uint64 value) {
  
  created_at_ = value;
  // @@protoc_insertion_point(field_set:minidfs.FileInfo.created_at)
}

// optional uint32 crc = 5;
inline void FileInfo::clear_crc() {
  crc_ = 0u;
}
inline ::google::protobuf::uint32 FileInfo::crc() const {
  // @@protoc_insertion_point(field_get:minidfs.FileInfo.crc)
  return crc_;
}
inline void FileInfo::set_crc(::google::protobuf::uint32 value) {
  
  crc_ = value;
  // @@protoc_insertion_point(field_set:minidfs.FileInfo.crc)
}

// -------------------------------------------------------------------

// ListAllFilesReq

// -------------------------------------------------------------------

// ListAllFilesRes

// repeated .minidfs.FileInfo files = 1;
inline int ListAllFilesRes::files_size() const {
  return files_.size();
}
inline void ListAllFilesRes::clear_files() {
  files_.Clear();
}
inline const ::minidfs::FileInfo& ListAllFilesRes::files(int index) const {
  // @@protoc_insertion_point(field_get:minidfs.ListAllFilesRes.files)
  return files_.Get(index);
}
inline ::minidfs::FileInfo* ListAllFilesRes::mutable_files(int index) {
  // @@protoc_insertion_point(field_mutable:minidfs.ListAllFilesRes.files)
  return files_.Mutable(index);
}
inline ::minidfs::FileInfo* ListAllFilesRes::add_files() {
  // @@protoc_insertion_point(field_add:minidfs.ListAllFilesRes.files)
  return files_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::minidfs::FileInfo >*
ListAllFilesRes::mutable_files() {
  // @@protoc_insertion_point(field_mutable_list:minidfs.ListAllFilesRes.files)
  return &files_;
}
inline const ::google::protobuf::RepeatedPtrField< ::minidfs::FileInfo >&
ListAllFilesRes::files() const {
  // @@protoc_insertion_point(field_list:minidfs.ListAllFilesRes.files)
  return files_;
}

// -------------------------------------------------------------------

// FileStatusReq

// optional string filepath = 1;
inline void FileStatusReq::clear_filepath() {
  filepath_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& FileStatusReq::filepath() const {
  // @@protoc_insertion_point(field_get:minidfs.FileStatusReq.filepath)
  return filepath_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FileStatusReq::set_filepath(const ::std::string& value) {
  
  filepath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:minidfs.FileStatusReq.filepath)
}
inline void FileStatusReq::set_filepath(const char* value) {
  
  filepath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:minidfs.FileStatusReq.filepath)
}
inline void FileStatusReq::set_filepath(const char* value, size_t size) {
  
  filepath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:minidfs.FileStatusReq.filepath)
}
inline ::std::string* FileStatusReq::mutable_filepath() {
  
  // @@protoc_insertion_point(field_mutable:minidfs.FileStatusReq.filepath)
  return filepath_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* FileStatusReq::release_filepath() {
  // @@protoc_insertion_point(field_release:minidfs.FileStatusReq.filepath)
  
  return filepath_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FileStatusReq::set_allocated_filepath(::std::string* filepath) {
  if (filepath != NULL) {
    
  } else {
    
  }
  filepath_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), filepath);
  // @@protoc_insertion_point(field_set_allocated:minidfs.FileStatusReq.filepath)
}

// -------------------------------------------------------------------

// WriteLockReq

// optional string client_id = 1;
inline void WriteLockReq::clear_client_id() {
  client_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& WriteLockReq::client_id() const {
  // @@protoc_insertion_point(field_get:minidfs.WriteLockReq.client_id)
  return client_id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void WriteLockReq::set_client_id(const ::std::string& value) {
  
  client_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:minidfs.WriteLockReq.client_id)
}
inline void WriteLockReq::set_client_id(const char* value) {
  
  client_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:minidfs.WriteLockReq.client_id)
}
inline void WriteLockReq::set_client_id(const char* value, size_t size) {
  
  client_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:minidfs.WriteLockReq.client_id)
}
inline ::std::string* WriteLockReq::mutable_client_id() {
  
  // @@protoc_insertion_point(field_mutable:minidfs.WriteLockReq.client_id)
  return client_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* WriteLockReq::release_client_id() {
  // @@protoc_insertion_point(field_release:minidfs.WriteLockReq.client_id)
  
  return client_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void WriteLockReq::set_allocated_client_id(::std::string* client_id) {
  if (client_id != NULL) {
    
  } else {
    
  }
  client_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), client_id);
  // @@protoc_insertion_point(field_set_allocated:minidfs.WriteLockReq.client_id)
}

// optional string filepath = 2;
inline void WriteLockReq::clear_filepath() {
  filepath_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& WriteLockReq::filepath() const {
  // @@protoc_insertion_point(field_get:minidfs.WriteLockReq.filepath)
  return filepath_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void WriteLockReq::set_filepath(const ::std::string& value) {
  
  filepath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:minidfs.WriteLockReq.filepath)
}
inline void WriteLockReq::set_filepath(const char* value) {
  
  filepath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:minidfs.WriteLockReq.filepath)
}
inline void WriteLockReq::set_filepath(const char* value, size_t size) {
  
  filepath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:minidfs.WriteLockReq.filepath)
}
inline ::std::string* WriteLockReq::mutable_filepath() {
  
  // @@protoc_insertion_point(field_mutable:minidfs.WriteLockReq.filepath)
  return filepath_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* WriteLockReq::release_filepath() {
  // @@protoc_insertion_point(field_release:minidfs.WriteLockReq.filepath)
  
  return filepath_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void WriteLockReq::set_allocated_filepath(::std::string* filepath) {
  if (filepath != NULL) {
    
  } else {
    
  }
  filepath_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), filepath);
  // @@protoc_insertion_point(field_set_allocated:minidfs.WriteLockReq.filepath)
}

// -------------------------------------------------------------------

// WriteLockRes

// optional bool success = 1;
inline void WriteLockRes::clear_success() {
  success_ = false;
}
inline bool WriteLockRes::success() const {
  // @@protoc_insertion_point(field_get:minidfs.WriteLockRes.success)
  return success_;
}
inline void WriteLockRes::set_success(bool value) {
  
  success_ = value;
  // @@protoc_insertion_point(field_set:minidfs.WriteLockRes.success)
}

// -------------------------------------------------------------------

// CallbackListReq

// optional string name = 1;
inline void CallbackListReq::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CallbackListReq::name() const {
  // @@protoc_insertion_point(field_get:minidfs.CallbackListReq.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CallbackListReq::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:minidfs.CallbackListReq.name)
}
inline void CallbackListReq::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:minidfs.CallbackListReq.name)
}
inline void CallbackListReq::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:minidfs.CallbackListReq.name)
}
inline ::std::string* CallbackListReq::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:minidfs.CallbackListReq.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CallbackListReq::release_name() {
  // @@protoc_insertion_point(field_release:minidfs.CallbackListReq.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CallbackListReq::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:minidfs.CallbackListReq.name)
}

// -------------------------------------------------------------------

// CallbackListRes

// optional uint64 version = 1;
inline void CallbackListRes::clear_version() {
  version_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 CallbackListRes::version() const {
  // @@protoc_insertion_point(field_get:minidfs.CallbackListRes.version)
  return version_;
}
inline void CallbackListRes::set_version(::google::protobuf::uint64 value) {
  
  version_ = value;
  // @@protoc_insertion_point(field_set:minidfs.CallbackListRes.version)
}

// repeated .minidfs.FileInfo files = 2;
inline int CallbackListRes::files_size() const {
  return files_.size();
}
inline void CallbackListRes::clear_files() {
  files_.Clear();
}
inline const ::minidfs::FileInfo& CallbackListRes::files(int index) const {
  // @@protoc_insertion_point(field_get:minidfs.CallbackListRes.files)
  return files_.Get(index);
}
inline ::minidfs::FileInfo* CallbackListRes::mutable_files(int index) {
  // @@protoc_insertion_point(field_mutable:minidfs.CallbackListRes.files)
  return files_.Mutable(index);
}
inline ::minidfs::FileInfo* CallbackListRes::add_files() {
  // @@protoc_insertion_point(field_add:minidfs.CallbackListRes.files)
  return files_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::minidfs::FileInfo >*
CallbackListRes::mutable_files() {
  // @@protoc_insertion_point(field_mutable_list:minidfs.CallbackListRes.files)
  return &files_;
}
inline const ::google::protobuf::RepeatedPtrField< ::minidfs::FileInfo >&
CallbackListRes::files() const {
  // @@protoc_insertion_point(field_list:minidfs.CallbackListRes.files)
  return files_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace minidfs

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_minidfs_2eproto__INCLUDED
